version: "3"
services:
    postgres:
        image: postgres:latest
        ports: 
            - 5432:5432
        container_name: "postgres"
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=GMT
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
    pgweb:
        image: sosedoff/pgweb
        ports:
            - 8081:8081
        links: 
            - postgres
        environment:
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
        depends_on: 
            - postgres